openapi: 3.0.0
info:
  title: foo
  version: '1.0'
  description: aaaa
servers:
  - url: 'http://localhost:3000'
paths:
  /foo:
    get:
      summary: get foo
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/access_token.v1.json
      operationId: get-foo
components:
  schemas: {}
